version: 1.5.{build}
image: Visual Studio 2019
configuration:
  - Release
before_build:
  - cmd: >-
    echo "111"

    nuget restore

    echo "222"

build:
  project: Tethys.Logging.sln
  verbosity: normal
test: off