# SPDX-FileCopyrightText: (c) 2022-2023 T. Graf
# SPDX-License-Identifier: Apache-2.0

version: 1.6.1.{build}
image: Visual Studio 2022
before_build:
- cmd: >-
    nuget restore
build:
  project: Tethys.Logging.sln
  verbosity: normal